name: "Aliyun OSS Upload"
description: "Upload files to Aliyun OSS"
author: "Vincent"
inputs:
  region:
    description: "ali-oss region"
    required: true
  accessKeyId:
    description: "ali-oss accessKeyId"
    required: true
  accessKeySecret:
    description: "ali-oss accessKeySecret"
    required: true
  bucket:
    description: "ali-oss bucket"
    required: true
  pattern:
    description: "glob pattern, The path to the asset you want to upload"
    required: true
  cwd:
    description: "glob cwd"
    required: false
  overwrite:
    description: "overwrite exist, default:true"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
